version: '3'

services:
  node0:
    container_name: colornode0
    image: "tendermint/colordnode"
    ports:
      - "26656-26657:26656-26657"
      - "60600:6060"
    environment:
      - ID=0
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.2

  node1:
    container_name: colornode1
    image: "tendermint/colordnode"
    ports:
      - "26658-26659:26656-26657"
      - "60601:6060"
    environment:
      - ID=1
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.3

  node2:
    container_name: colornode2
    image: "tendermint/colordnode"
    ports:
      - "26660-26661:26656-26657"
      - "60602:6060"
    environment:
      - ID=2
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.4

  node3:
    container_name: colornode3
    image: "tendermint/colordnode"
    ports:
      - "26662-26663:26656-26657"
      - "60603:6060"
    environment:
      - ID=3
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.5

  node4:
    container_name: colornode4
    image: "tendermint/colordnode"
    ports:
      - "26664-26665:26656-26657"
      - "60604:6060"
    environment:
      - ID=4
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.6

  node5:
    container_name: colornode5
    image: "tendermint/colordnode"
    ports:
      - "26666-26667:26656-26657"
      - "60605:6060"
    environment:
      - ID=5
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.7

  node6:
    container_name: colornode6
    image: "tendermint/colordnode"
    ports:
      - "26668-26669:26656-26657"
      - "60606:6060"
    environment:
      - ID=6
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.8

  node7:
    container_name: colornode7
    image: "tendermint/colordnode"
    ports:
      - "26670-26671:26656-26657"
      - "60607:6060"
    environment:
      - ID=7
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.9

  node8:
    container_name: colornode8
    image: "tendermint/colordnode"
    ports:
      - "26672-26673:26656-26657"
      - "60608:6060"
    environment:
      - ID=8
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.10

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.165.0.0/24

