version: '3'

services:
  node0:
    container_name: colornode0
    image: "tendermint/colordnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.2

  node1:
    container_name: colornode1
    image: "tendermint/colordnode"
    ports:
      - "26658-26659:26656-26657"
    environment:
      - ID=1
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.3

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.165.0.0/24

