version: '3'

services:
  node0:
    container_name: colornode0
    image: "tendermint/colordnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.2

  node1:
    container_name: colornode1
    image: "tendermint/colordnode"
    ports:
      - "26658-26659:26656-26657"
    environment:
      - ID=1
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.3

  node2:
    container_name: colornode2
    image: "tendermint/colordnode"
    ports:
      - "26660-26661:26656-26657"
    environment:
      - ID=2
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.4

  node3:
    container_name: colornode3
    image: "tendermint/colordnode"
    ports:
      - "26662-26663:26656-26657"
    environment:
      - ID=3
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.5

  node4:
    container_name: colornode4
    image: "tendermint/colordnode"
    ports:
      - "26664-26665:26656-26657"
    environment:
      - ID=4
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.6

  node5:
    container_name: colornode5
    image: "tendermint/colordnode"
    ports:
      - "26666-26667:26656-26657"
    environment:
      - ID=5
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.7

  node6:
    container_name: colornode6
    image: "tendermint/colordnode"
    ports:
      - "26668-26669:26656-26657"
    environment:
      - ID=6
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.8

  node7:
    container_name: colornode7
    image: "tendermint/colordnode"
    ports:
      - "26670-26671:26656-26657"
    environment:
      - ID=7
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.9

  node8:
    container_name: colornode8
    image: "tendermint/colordnode"
    ports:
      - "26672-26673:26656-26657"
    environment:
      - ID=8
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.10

  node9:
    container_name: colornode9
    image: "tendermint/colordnode"
    ports:
      - "26674-26675:26656-26657"
    environment:
      - ID=9
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.11

  node10:
    container_name: colornode10
    image: "tendermint/colordnode"
    ports:
      - "26676-26677:26656-26657"
    environment:
      - ID=10
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.12

  node11:
    container_name: colornode11
    image: "tendermint/colordnode"
    ports:
      - "26678-26679:26656-26657"
    environment:
      - ID=11
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.13

  node12:
    container_name: colornode12
    image: "tendermint/colordnode"
    ports:
      - "26680-26681:26656-26657"
    environment:
      - ID=12
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.14

  node13:
    container_name: colornode13
    image: "tendermint/colordnode"
    ports:
      - "26682-26683:26656-26657"
    environment:
      - ID=13
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.15

  node14:
    container_name: colornode14
    image: "tendermint/colordnode"
    ports:
      - "26684-26685:26656-26657"
    environment:
      - ID=14
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.16

  node15:
    container_name: colornode15
    image: "tendermint/colordnode"
    ports:
      - "26686-26687:26656-26657"
    environment:
      - ID=15
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.17

  node16:
    container_name: colornode16
    image: "tendermint/colordnode"
    ports:
      - "26688-26689:26656-26657"
    environment:
      - ID=16
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.18

  node17:
    container_name: colornode17
    image: "tendermint/colordnode"
    ports:
      - "26690-26691:26656-26657"
    environment:
      - ID=17
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.19

  node18:
    container_name: colornode18
    image: "tendermint/colordnode"
    ports:
      - "26692-26693:26656-26657"
    environment:
      - ID=18
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.20

  node19:
    container_name: colornode19
    image: "tendermint/colordnode"
    ports:
      - "26694-26695:26656-26657"
    environment:
      - ID=19
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.21

  node20:
    container_name: colornode20
    image: "tendermint/colordnode"
    ports:
      - "26696-26697:26656-26657"
    environment:
      - ID=20
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.22

  node21:
    container_name: colornode21
    image: "tendermint/colordnode"
    ports:
      - "26698-26699:26656-26657"
    environment:
      - ID=21
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.23

  node22:
    container_name: colornode22
    image: "tendermint/colordnode"
    ports:
      - "26700-26701:26656-26657"
    environment:
      - ID=22
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.24

  node23:
    container_name: colornode23
    image: "tendermint/colordnode"
    ports:
      - "26702-26703:26656-26657"
    environment:
      - ID=23
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.25

  node24:
    container_name: colornode24
    image: "tendermint/colordnode"
    ports:
      - "26704-26705:26656-26657"
    environment:
      - ID=24
      - LOG=colord.log
      - COMMAND_ARGS
      - SUBCOMMAND_ARGS
    volumes:
      - ./build:/colord:Z
    networks:
      localnet:
        ipv4_address: 192.165.0.26

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.165.0.0/24

